# Generated by Django 4.2 on 2025-05-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_table_billmaster_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table_billitems",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="table_accountsmaster",
            unique_together={("user", "head")},
        ),
    ]
