# Generated by Django 4.2 on 2025-05-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_table_billitems_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table_companydetailsmaster",
            name="user",
        ),
    ]
