# Generated by Django 4.2 on 2025-05-09 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_table_companydetailsmaster_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table_accountsmaster",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
