# Generated by Django 4.2 on 2025-05-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_table_billmaster_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_billmaster",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.table_companydetailsmaster",
            ),
        ),
    ]
