# Generated by Django 4.2 on 2025-05-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_table_billmaster_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table_FormattedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iform_id", models.PositiveIntegerField()),
                ("form_name", models.CharField(max_length=50)),
                ("vconfiq_value", models.CharField(max_length=70)),
                ("vdb_field", models.CharField(max_length=70)),
                (
                    "account_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_accountsmaster",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxMaster",
            fields=[
                ("tax_code", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=44)),
                ("tax_type", models.CharField(max_length=18)),
                ("tax_perc", models.FloatField()),
                ("account_head", models.CharField(max_length=125)),
                ("status", models.CharField(max_length=10)),
                ("account_code", models.IntegerField()),
                ("group_code", models.IntegerField(blank=True, null=True)),
                (
                    "tax_category",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("co_id", models.CharField(max_length=5)),
                ("fy_code", models.CharField(max_length=15)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_accountsmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iconfiq_id", models.PositiveIntegerField()),
                ("iacc_id", models.CharField(max_length=200)),
                ("drcr", models.CharField(max_length=8)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_formattedconfig",
                    ),
                ),
            ],
        ),
    ]
