# Generated by Django 4.2 on 2025-05-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_table_formattedconfig_taxmaster_table_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=100)),
                ("subunit", models.CharField(max_length=100)),
                ("conv_factor", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_group", models.CharField(max_length=200)),
                (
                    "item_subgroup",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("primary_group", models.CharField(default="N", max_length=5)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GodownMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("godown", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
            ],
        ),
    ]
