# Generated by Django 4.2 on 2025-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_unitmaster_groupmaster_godownmaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip_sheet",
            name="advance_driver",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="advance_from_customer",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="battery",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="diesel_charges",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="diesel_ltr",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="driver_bata",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="ending_km",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="filling_km",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="fixed_charge_total",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="km_rate",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="mech_electric",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="starting_km",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="statutory_charge",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="total_freight_charges",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="total_km",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="trip_sheet",
            name="tyre_work",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
