# Generated by Django 4.2 on 2025-05-31 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_trip_sheet_advance_driver_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Table_Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Series", models.CharField(blank=True, max_length=255, null=True)),
                ("VoucherNo", models.IntegerField(blank=True, null=True)),
                ("Vdate", models.DateField(blank=True, null=True)),
                (
                    "Accountcode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Headcode", models.CharField(blank=True, max_length=255, null=True)),
                ("CStatus", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "VAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("VType", models.CharField(blank=True, max_length=255, null=True)),
                ("Narration", models.TextField(blank=True, null=True)),
                ("UserID", models.CharField(blank=True, max_length=255, null=True)),
                ("FYCode", models.CharField(blank=True, max_length=255, null=True)),
                ("Coid", models.CharField(blank=True, max_length=255, null=True)),
                ("Branch_ID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_Journal_Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(blank=True, max_length=100, null=True)),
                ("voucher_no", models.IntegerField(blank=True, null=True)),
                ("vdate", models.DateField(blank=True, null=True)),
                (
                    "accountcode",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "dramount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=50, null=True
                    ),
                ),
                (
                    "cramount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=50, null=True
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("fycode", models.CharField(blank=True, max_length=100, null=True)),
                ("coid", models.CharField(blank=True, max_length=100, null=True)),
                ("brid", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "auth_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_DrCrNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(blank=True, max_length=150, null=True)),
                ("noteno", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "ndate",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "accountcode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("narration", models.CharField(blank=True, max_length=200, null=True)),
                ("dramount", models.CharField(blank=True, max_length=230, null=True)),
                ("cramount", models.CharField(blank=True, max_length=230, null=True)),
                ("ntype", models.CharField(blank=True, max_length=1, null=True)),
                ("userid", models.CharField(blank=True, max_length=25, null=True)),
                ("coid", models.CharField(blank=True, max_length=1, null=True)),
                ("fycode", models.CharField(blank=True, max_length=15, null=True)),
                ("brid", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table_Contra_Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(blank=True, max_length=100, null=True)),
                ("voucher_no", models.IntegerField(blank=True, null=True)),
                ("vdate", models.DateField(blank=True, null=True)),
                (
                    "accountcode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "dramount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=50, null=True
                    ),
                ),
                (
                    "cramount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=50, null=True
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("fycode", models.CharField(blank=True, max_length=100, null=True)),
                ("coid", models.CharField(blank=True, max_length=100, null=True)),
                ("brid", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "auth_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AccountCode", models.CharField(blank=True, max_length=15, null=True)),
                ("VoucherType", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "VoucherSeries",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("VoucherNo", models.IntegerField(blank=True, null=True)),
                ("FormType", models.CharField(blank=True, max_length=15, null=True)),
                ("Narration", models.CharField(blank=True, max_length=255, null=True)),
                ("Amount", models.IntegerField(blank=True, null=True)),
                ("Dr_Cr", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "FinancialYear",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("BranchID", models.CharField(blank=True, max_length=15, null=True)),
                ("CompanyID", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.table_companydetailsmaster",
                    ),
                ),
            ],
        ),
    ]
