# Generated by Django 5.0.3 on 2025-09-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_ratemaster_ratechild"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratechild",
            name="additional_charge",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratechild",
            name="fixed_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratechild",
            name="km",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratechild",
            name="type",
            field=models.CharField(default="Km wise", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ratechild",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
