# Generated by Django 5.0.3 on 2025-09-23 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_ratechild_additional_charge_ratechild_fixed_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_accountsmaster",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branch_master",
            ),
        ),
        migrations.AddField(
            model_name="table_accountsmaster",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.table_companydetailsmaster",
            ),
        ),
        migrations.AlterField(
            model_name="table_accountsmaster",
            name="group",
            field=models.CharField(
                choices=[
                    ("LIABILITIES", "LIABILITIES"),
                    ("INCOME", "INCOME"),
                    ("EXPENSES", "EXPENSES"),
                    ("TRADING EXPENSES", "TRADING EXPENSES"),
                    ("TRADING INCOME", "TRADING INCOME"),
                    ("CURRENT ASSET", "CURRENT ASSET"),
                    ("FIXED ASSETS", "FIXED ASSETS"),
                    ("CURRENT LIABILITIES", "CURRENT LIABILITIES"),
                    ("INDIRECT INCOME", "INDIRECT INCOME"),
                    ("INDIRECT EXPENSES", "INDIRECT EXPENSES"),
                    ("SUNDRY DEBTORS", "SUNDRY DEBTORS"),
                    ("SUNDRY CREDITORS", "SUNDRY CREDITORS"),
                    ("CASH AT BANK", "CASH AT BANK"),
                    ("CASH IN HAND", "CASH IN HAND"),
                    ("DUTIES AND TAXES", "DUTIES AND TAXES"),
                    ("LOANS", "LOANS"),
                    ("CAPITAL ACCOUNT", "CAPITAL ACCOUNT"),
                ],
                max_length=249,
            ),
        ),
        migrations.AlterField(
            model_name="table_accountsmaster",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="table_accountsmaster",
            name="tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="table_accountsmaster",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="table_acntchild",
            name="branch_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="table_acntchild",
            name="company_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="table_acntchild",
            name="current_balance",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="table_acntchild",
            name="fyc_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
