# Generated by Django 5.0.3 on 2025-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_table_accountsmaster_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip_sheet",
            name="rate_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
