# Generated by Django 5.0.3 on 2025-09-25 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_trip_sheet_rate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="table_billitems",
            name="total_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table_billmaster",
            name="additional_charges",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="table_billmaster",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.branch_master",
            ),
        ),
        migrations.AddField(
            model_name="table_billmaster",
            name="fy_code",
            field=models.CharField(default="2025-2026", max_length=15),
        ),
        migrations.AddField(
            model_name="table_billmaster",
            name="rate_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="table_billmaster",
            name="total_km",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
