# Generated by Django 4.2 on 2025-09-26 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_table_billitems_total_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_point', models.CharField(max_length=200)),
                ('unloading_point', models.CharField(max_length=200)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch_master')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.table_companydetailsmaster')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehicle_type')),
            ],
        ),
    ]
