# Generated by Django 4.2 on 2025-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_vendormaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmaster',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
