# Generated by Django 4.2 on 2025-09-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_locationmaster_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmaster',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
